base:
  - &base-ts
    length: 5000
    channels: 1
    semi-supervised: true
    supervised: true
  - &base-osci
    frequency: 5.0
    amplitude: 1.0
    variance: 0.05

sine:
  - &sine-0
    <<: *base-osci
    kind: "sine"


anomaly_kinds:
  - &platform
    length: 100
    kinds:
      - kind: "platform"
        parameters:
          value: 0.0

studies:
  - name: Series2Graph
    algorithm: series2graph
    ntrials: 10
    timeseries:
      - sine-noise-50%
    parameters:
      - name: anomaly_window_size
        dtype: int
        min: 4
        max: 50
      - name: exclusion_zone
        dtype: float
        min: 0.01
        max: 0.99

  # - name: Series2Graph
  #   image: mut:5000/akita/series2graph
  #   ntrials: 100
  #   timeseries:
  #     - sine-noise-10%
  #   parameters:
  #     - name: window_size
  #       dtype: int
  #       min: 30
  #       max: 70
  #     - name: query_window_size
  #       dtype: int
  #       min: 50
  #       max: 100
  #     - name: rate
  #       dtype: int
  #       min: 10
  #       max: 50
  # - name: K Nearest Neighbors (KNN)
  #   executable: knn
  #   ntrials: 120
  #   timeseries:
  #     # - sine-noise-00%
  #     # - sine-noise-01%
  #     # - sine-noise-10%
  #     # - sine-noise-30%
  #     # - sine-noise-50%
  #   parameters:
  #     - name: n_neighbors
  #       dtype: int
  #       min: 1
  #       max: 20
  #     - name: algorithm
  #       dtype: category
  #       values:
  #         - ball_tree
  #         - kd_tree
  #         - brute
  #     - name: leaf_size
  #       dtype: int
  #       min: 10
  #       max: 50
  #     - name: method
  #       dtype: category
  #       values:
  #         - largest
  #         - mean
  #         - median
  #     - name: radius
  #       dtype: float
  #       min: 0.1
  #       max: 2.0
  #     - name: p
  #       dtype: int
  #       min: 1
  #       max: 5
timeseries:
  - name: sine-noise-50%
    <<: *base-ts
    base-oscillation:
      <<: *sine-0
      variance: 0.5
    anomalies:
      - *platform
