version: '3.5'
services:
  controller:
    container_name: hypex_controller
    image: hypex-controller
    tty: true
    volumes:
      - .:/usr/src/hypex

  sopedu:
    image: registry:2
    ports:
      - 5000:5000

  node-0:
    container_name: hypex_node-0
    image: hypex-node
    privileged: true
    ports:
      - 6379:6379 # Redis
      - 8787:8787 # Dask Dashboard
      - 8080:8080 # Optuna Dashboard
    volumes:
      - .local/node-0/:/home/admin/:rw

  node-1:
    container_name: hypex_node-1
    privileged: true
    image: hypex-node
    ports:
      - 34443:34443
    volumes:
      - .local/node-1/:/home/admin/:rw
