version: '3.5'
services:
  controller:
    container_name: hypaad_controller
    image: hypaad-controller
    tty: true
    volumes:
      - .:/usr/src/hypaad

  sopedu:
    image: registry:2
    ports:
      - 5000:5000

  node-0:
    container_name: hypaad_node-0
    image: hypaad-node
    privileged: true
    ports:
      - 6379:6379 # Redis
      - 8787:8787 # Dask Dashboard
      - 8080:8080 # Optuna Dashboard

  node-1:
    container_name: hypaad_node-1
    privileged: true
    image: hypaad-node
    ports:
      - 34443:34443
