type: object
properties:
  studies:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        algorithm:
          type: string
        n_trials:
          type: object
          properties:
            train:
              type: integer
            validation:
              type: integer
            test:
              type: integer
        timeseries:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              n_mutations:
                type: integer
              mutations:
                type: array
                items:
                  type: object
                  properties:
                    path:
                      type: string
                    dtype:
                      type: string
                    min:
                      type: number
                    max:
                      type: number
        parameters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              dtype:
                type: string
              min:
                type: number
              min_exclusive:
                type: boolean
              max:
                type: number



