name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Python 3.10 is currently not supported since statsmodels==0.12.* cannot be installed
        python-version: ["3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        make setupCI
        python -m pip install git+https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.hpi.de/mats.poerschke/guten-tag.git
        python -m pip install git+https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.hpi.de/mats.poerschke/timeeval.git
    - name: Lint
      run: make lint
    - name: Test
      run: make test
